example_setting:
  default: true
  description:
    en: A description of a setting.
valid_tags:
  default: completed|feature
  type: list
category_id:
  default: 1
disclosure_text:
  default: By submitting a post, you agree to the terms and conditions of this forum.
